import { useCallback, useMemo, useState } from 'react';
import { Bell, Search, Info, MailOpen, Mail } from 'lucide-react';
import { activityTypeLabel, fetchActivity } from '@/lib/api/activity';
import { useLiveQuery } from '@/lib/useLiveQuery';
import { formatRelative } from '@/lib/format';
import type { ActivityItem } from '@/lib/types';
import { PageHeader } from '@/components/ui/PageHeader';
import { Badge } from '@/components/ui/Badge';
import { Avatar } from '@/components/ui/Avatar';
import { StatCard } from '@/components/ui/StatCard';
import { LoadingState, ErrorState, EmptyState } from '@/components/ui/States';

/** Groups the many notification types into a few colours so the feed scans. */
function variantFor(item: ActivityItem): 'primary' | 'secondary' | 'accent' | 'neutral' {
  if (item.type.startsWith('connection')) return 'primary';
  if (item.type.startsWith('post') || item.type.startsWith('org_post')) return 'secondary';
  if (item.type.startsWith('event')) return 'accent';
  return 'neutral';
}

export function ActivityPage() {
  const fetcher = useCallback(() => fetchActivity(), []);
  const { data, loading, error, refetch } = useLiveQuery(fetcher, ['notifications']);

  const [search, setSearch] = useState('');
  const [typeFilter, setTypeFilter] = useState('all');

  const items = useMemo(() => data ?? [], [data]);

  const types = useMemo(
    () => [...new Set(items.map((item) => item.type))].sort(),
    [items]
  );

  const unread = useMemo(() => items.filter((item) => !item.isRead).length, [items]);

  const filtered = useMemo(() => {
    const term = search.trim().toLowerCase();
    return items.filter((item) => {
      const haystack = [item.actorName, item.message, item.relatedEntityName, item.recipient?.name]
        .filter(Boolean)
        .join(' ')
        .toLowerCase();
      const matchesSearch = !term || haystack.includes(term);
      const matchesType = typeFilter === 'all' || item.type === typeFilter;
      return matchesSearch && matchesType;
    });
  }, [items, search, typeFilter]);

  if (loading) return <LoadingState label="Loading activity..." />;
  if (error) return <ErrorState message={error} onRetry={refetch} />;

  return (
    <div>
      <PageHeader title="Activity" description="Notifications delivered across the platform" />

      {/*
        The notifications table is the app's per-user activity feed, written by
        the mobile app and its edge functions. There is no admin write policy,
        and no broadcast/scheduling columns — so this is an observation surface,
        not a composer.
      */}
      <div className="card p-3 mb-6 flex items-start gap-2.5 text-xs text-dark-400">
        <Info size={15} className="text-dark-500 flex-shrink-0 mt-0.5" />
        <span>
          This is the platform&apos;s live activity feed, generated by the UPlay app. It is read-only
          here — the console doesn&apos;t send notifications.
        </span>
      </div>

      <div className="grid gap-4 sm:grid-cols-3 mb-6">
        <StatCard label="Total" value={items.length} icon={<Bell size={22} />} />
        <StatCard label="Unread" value={unread} icon={<Mail size={22} />} color="warning" />
        <StatCard
          label="Read"
          value={items.length - unread}
          icon={<MailOpen size={22} />}
          color="secondary"
        />
      </div>

      <div className="card p-4 mb-6 flex flex-col sm:flex-row gap-3">
        <div className="relative flex-1">
          <Search size={18} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-dark-400" />
          <input
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search activity"
            className="input-field pl-11"
          />
        </div>
        <select
          value={typeFilter}
          onChange={(e) => setTypeFilter(e.target.value)}
          className="input-field sm:w-52"
        >
          <option value="all">All types</option>
          {types.map((type) => (
            <option key={type} value={type}>
              {activityTypeLabel(type)}
            </option>
          ))}
        </select>
      </div>

      {filtered.length === 0 ? (
        <EmptyState
          icon={<Bell size={28} />}
          title="No activity match"
          description={
            items.length === 0
              ? 'No notifications have been generated yet.'
              : 'Try clearing the search or filter.'
          }
        />
      ) : (
        <div className="space-y-2">
          {filtered.map((item) => (
            <div
              key={item.id}
              className={`card p-4 flex items-start gap-3 hover:border-dark-700 transition-colors ${
                item.isRead ? '' : 'border-l-2 border-l-primary-500'
              }`}
            >
              <Avatar name={item.actorName ?? 'System'} url={item.actorAvatarUrl} size={36} />

              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 flex-wrap">
                  <Badge variant={variantFor(item)}>{activityTypeLabel(item.type)}</Badge>
                  {!item.isRead && <span className="w-1.5 h-1.5 rounded-full bg-primary-400" />}
                  <span className="text-xs text-dark-500">{formatRelative(item.createdAt)}</span>
                </div>

                <p className="text-sm text-dark-200 mt-1.5 break-words">
                  {item.message ?? <span className="italic text-dark-500">No message</span>}
                </p>

                <div className="flex items-center gap-3 mt-1.5 text-xs text-dark-500 flex-wrap">
                  {item.actorName && <span>From {item.actorName}</span>}
                  {item.recipient && <span>To {item.recipient.name}</span>}
                  {item.relatedEntityName && <span>Re: {item.relatedEntityName}</span>}
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
